name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint app
        working-directory: ./app
        run: |
          npm ci
          npm run lint
      - name: Lint server
        working-directory: ./server
        run: |
          npm ci
          npm run lint
