name: AWS SAM Build
on: pull_request
jobs:
  sam-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Installing python is required for setting up AWS SAM
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v1
        
      - name: SAM Build
        working-directory: ./server
        run: |
          sam build --use-container