name: AWS SAM Validate, Build, Deploy
on:
  push:
    branches: [ main ]

jobs:
  sam-validate-build-package-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: SAM Validate
        run: |
          sam validate

      - name: SAM Build
        run: |
          sam build --use-container

      - name: SAM Package
        run: |
          sam package \
            --output-template-file packaged-template.yaml \
            --image-repository ${{ secrets.AWS_SAM_IMAGE_REPOSITORY_URL }}

      - name: SAM Deploy
        run: |
          sam deploy 
            --template-file ./packaged-template.yaml \
            --stack-name ${{ secrets.AWS_SAM_STACK_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --image-repository ${{ secrets.AWS_SAM_IMAGE_REPOSITORY_URL }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
            --no-confirm-changeset 
            --no-fail-on-empty-changeset